version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo "🔧 Installing Docker..."
      - yum update -y
      - yum install -y docker
      - service docker start
      - echo "✅ Docker installed."

  build:
    commands:
      - echo "📂 Listing files..."
      - ls -al
      - echo "🚀 Building Docker images using docker-compose..."
      - docker-compose -f docker-compose.yml build
      - echo "✅ Docker images built."

  post_build:
    commands:
      - echo "📦 Starting Docker containers..."
      - docker-compose -f docker-compose.yml up -d
      - echo "✅ Containers started."

artifacts:
  files:
    - '**/*'
