version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ranjan_backend
    ports:
      - "5000:5000"
    restart: always
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ranjan_frontend
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production

  mongo:
    image: mongo:latest
    container_name: ranjan_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
