version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/ranjan_healthcare
      - EMAIL_USER=yourgmail@gmail.com
      - EMAIL_PASS=your_app_password
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
